build:
  image: framgia/laravel-workspace
  commands:
    - cp .env.ci.example .env
    - composer install
    - php artisan key:generate
    - chmod -R 755 storage/*
    - php artisan migrate
    - php artisan passport:install
    - framgia-ci test-connect 127.0.0.1 3306 60
    - framgia-ci run

compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: f_campaign
      MYSQL_USER: campaign
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - vendor
    - .git
